### ISSUE TITLE
Multiword Tags

### ISSUE THREAD

**Issue by thunderysteak** [Orangestar12/cacobot#6]
If I want to create a tag with the bot that is more than just a single word, the bot saves only the first word in the text. 
For example ".tag create SYN 'SYN ACK'" results only in "SYN" when ".tag SYN" is used.

**Comment by Orangestar12** [comment]
Tags is a piece of crap and needs to be rewritten. For now, implicitly creating tags (`.tag bepis You're drooling!`) should provide the solution you want.

**Comment by Orangestar12** [comment]
I was hoping to rewrite tags completely but I ended up finding the bug and fixing it anyway because this rewrite is hurting my brain to process.

Determinate's rewrite is gonna be much, much harder.

Anyway, fix for this should be in the code and on cb now. Thanks for your insane patience.
